version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
#    networks:
#      - MONGO
    volumes:
      - /usr/mongodb/data:/data/db
    ports:
      - "27017:27017"
      -
  server:
    container_name: god_server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/usr/godapp/server/src
    depends_on:
      - "mongo"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
#    networks:
#      - MONGO
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - '8081:8081'
    volumes:
      - /usr/mongodb/data:/data/db

networks:
  default:
    name: mongo-express-network